[package]
name = "fennec-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fennec-interner = { path = "../interner" }
fennec-source = { path = "../source" }
fennec-reporting = { path = "../reporting" }
fennec-semantics = { path = "../semantics" }
fennec-linter = { path = "../linter" }
fennec-reflection = { path = "../reflection" }
fennec-reflector = { path = "../reflector" }
fennec-span = { path = "../span" }
fennec-feedback = { path = "../feedback" }
fennec-formatter = { path = "../formatter" }
fennec-ast = { path = "../ast" }
fennec-parser = { path = "../parser" }
tokio = { workspace = true }
serde = { workspace = true }
ahash = { workspace = true }
async-walkdir = { workspace = true }
futures = { workspace = true }
glob-match = { workspace = true }
tracing = { workspace = true }
config = { workspace = true }
toml = { workspace = true }
num_cpus = { workspace = true }
