[package]
name = "fennec-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fennec-interner = { path = "../interner" }
fennec-source = { path = "../source" }
fennec-reporting = { path = "../reporting" }
fennec-semantics = { path = "../semantics" }
fennec-linter = { path = "../linter" }
fennec-config = { path = "../config" }
fennec-reflection = { path = "../reflection" }
fennec-reflector = { path = "../reflector" }
fennec-feedback = { path = "../feedback" }
tokio = { workspace = true }
serde = { workspace = true }
