[package]
name = "fennec-source"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fennec-interner = { path = "../interner" }
codespan-reporting = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
