[package]
name = "fennec-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
getrandom = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
fennec-ast = { path = "../ast" }
fennec-names = { path = "../names" }
fennec-interner = { path = "../interner" }
fennec-reporting = { path = "../reporting" }
fennec-semantics = { path = "../semantics" }
fennec-symbol-table = { path = "../symbol-table" }
fennec-source = { path = "../source" }
fennec-parser = { path = "../parser" }
fennec-formatter = { path = "../formatter" }
